# Generated by Django 3.0.7 on 2020-09-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200904_2000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdutCategory',
            new_name='ProductCategory',
        ),
    ]
